logging:
  level:
    org:
      springframework:
        security: debug

spring:
  application.name: hub
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor-db
    username: user
    password: password
  cloud.stream.bindings:
    receiveSensorData-in-0.destination: sensor-data
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        add-additional-paths: true
        enabled: true
