apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-sensors-hub
  namespace: my-apps
  labels:
    app.kubernetes.io/part-of: tap-sensors
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/d-lorenc/tap-sensors.git
      ref:
        branch: main
    subPath: hub
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: sensors-rabbit
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: sensors-rabbit-claim
    - name: sensors-db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: sensors-db-claim
