apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-sensors-hub
  namespace: apps
  labels:
    app.kubernetes.io/part-of: tap-sensors
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/gpstines/tap-sensors.git
      ref:
        branch: tap-developer-sandbox
    subPath: hub
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: sensors-rabbit
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: sensors-rabbit-claim
    - name: sensors-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: sensors-db-claim
    - name: sso
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: appsso-tap-sensor-hub
    - name: sensor-redis
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: sensors-redis