apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-sensors-sensor
  namespace: apps
  labels:
    app.kubernetes.io/part-of: tap-sensors
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/d-lorenc/tap-sensors.git
      ref:
        branch: tap-developer-sandbox
    subPath: sensor
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "3"
  serviceClaims:
    - name: sensors-rabbit
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: sensors-rabbit-claim
