spring:
  cloud:
    gateway:
      routes:
        - id: hub_api_route
          uri: http://tap-sensors-hub.apps.svc.cluster.local/api/
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
        - id: hub_ui_route
          uri: http://hub-ui.apps.svc.cluster.local/api/
          predicates:
            - Path=/**
    # TODO Add TokenRelay default filter thing