apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  namespace: apps
  labels:
    apps.tanzu.vmware.com/pipeline: java-monorepo-test
spec:
  params:
    - name: source-url
    - name: source-revision
    - name: subpath
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: subpath
          value: $(params.subpath)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
          - name: subpath
        steps:
          - name: test
            image: gradle
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              cd $(params.subpath)
              ./gradlew test --info
