#@ load("@ytt:overlay", "overlay")

#@ def renameSupplyChain(original, _):
#@  origCopy = dict(**original)
#@  origCopy["ootb_supply_chain_testing_scanning"] = original["ootb_supply_chain_basic"]
#@  origCopy.pop("ootb_supply_chain_basic")
#@  return origCopy
#@ end

#! This first block is just to rename the supply chain key to a different name but keep the existing values
#@overlay/match by=overlay.all, expects=1
#@overlay/replace via=renameSupplyChain
---

#! This second block applies any overrides needed
#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
supply_chain: testing_scanning

scanning:
  resources:
    limits:
      cpu: "500m"
      memory: 3Gi
    requests:
      cpu: 200m
      memory: 1Gi
